# Generated by Django 5.0.7 on 2024-07-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_asset', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('furniture', 'Furniture'), ('other', 'Other')], max_length=50)),
                ('specifications', models.TextField()),
                ('date_of_purchase', models.DateField()),
                ('make_and_model', models.CharField(max_length=100)),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class', 'G1 Class'), ('g2_class', 'G2 Class')], max_length=50)),
            ],
        ),
    ]
