# Generated by Django 5.0.7 on 2024-08-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(default='TEMP_ID', max_length=50)),
                ('hardware_type', models.CharField(default='computer', max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('processor', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=50)),
                ('processor_generation', models.CharField(choices=[('1st Gen', '1st Gen'), ('2nd Gen', '2nd Gen'), ('3rd Gen', '3rd Gen'), ('4th Gen', '4th Gen'), ('5th Gen', '5th Gen'), ('6th Gen', '6th Gen'), ('7th Gen', '7th Gen'), ('8th Gen', '8th Gen'), ('9th Gen', '9th Gen'), ('10th Gen', '10th Gen'), ('11th Gen', '11th Gen'), ('12th Gen', '12th Gen'), ('13th Gen', '13th Gen'), ('14th Gen', '14th Gen'), ('15th Gen', '15th Gen')], max_length=50)),
                ('ram', models.CharField(choices=[('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB')], max_length=50)),
                ('rom', models.CharField(blank=True, max_length=50)),
                ('motherboard', models.CharField(blank=True, max_length=50)),
                ('power_supply', models.CharField(blank=True, max_length=50)),
                ('graphics_card', models.CharField(blank=True, max_length=50)),
                ('date_of_purchase', models.DateField(default='2000-01-01')),
                ('stock_register_number', models.CharField(default='0000', max_length=50)),
                ('account_head', models.CharField(default='Default Account Head', max_length=100)),
                ('location', models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class_first_year', 'G1 Class First Year'), ('g1_class_second_year', 'G1 Class Second Year'), ('g2_class_first_year', 'G2 Class First Year'), ('g2_class_second_year', 'G2 Class Second Year'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], default='isl_lab', max_length=50)),
            ],
        ),
    ]
