# Generated by Django 5.0.7 on 2024-08-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0002_computerhardware'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(default='TEMP_ID', max_length=50)),
                ('brand', models.CharField(blank=True, default='Brand', max_length=50)),
                ('model', models.CharField(blank=True, default='Model', max_length=50)),
                ('resolution', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('4K', '4K')], default='1080p', max_length=10)),
                ('lumens', models.IntegerField(default=2000)),
                ('contrast_ratio', models.CharField(blank=True, default='1000:1', max_length=20)),
                ('connectivity', models.CharField(choices=[('HDMI', 'HDMI'), ('VGA', 'VGA'), ('DVI', 'DVI'), ('USB', 'USB'), ('Wireless', 'Wireless')], default='HDMI', max_length=50)),
                ('lamp_life_hours', models.IntegerField(default=2000)),
                ('date_of_purchase', models.DateField(default='2000-01-01')),
                ('stock_register_number', models.CharField(default='0000', max_length=50)),
                ('account_head', models.CharField(default='Default Account Head', max_length=100)),
                ('location', models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class_first_year', 'G1 Class First Year'), ('g1_class_second_year', 'G1 Class Second Year'), ('g2_class_first_year', 'G2 Class First Year'), ('g2_class_second_year', 'G2 Class Second Year'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], default='isl_lab', max_length=50)),
                ('type_of_asset', models.CharField(default='hardware', max_length=50)),
            ],
        ),
    ]
