# Generated by Django 5.0.7 on 2024-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0002_alter_asset_location_alter_asset_type_of_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ASSET_ID',
            field=models.CharField(default='TEMP_ID', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='graphics_card',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='hardware_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='motherboard',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='power_supply',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='processor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='rom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class_first_year', 'G1 Class First Year'), ('g1_class_second_year', 'G1 Class Second Year'), ('g2_class_first_year', 'G2 Class First Year'), ('g2_class_second_year', 'G2 Class Second Year'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='make_and_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type_of_asset',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('computer_peripherals', 'Computer Peripherals'), ('furniture', 'Furniture'), ('book', 'Books'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], max_length=50),
        ),
    ]
