# Generated by Django 5.0.7 on 2024-08-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0003_projector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(default='TEMP_ID', max_length=50)),
                ('type_of_asset', models.CharField(default='Book', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publishing_house', models.CharField(max_length=255)),
                ('edition', models.CharField(blank=True, default='1.0', max_length=50, null=True)),
                ('date_of_purchase', models.DateField(default='2000-01-01')),
                ('stock_register_number', models.CharField(default='0000', max_length=50)),
                ('account_head', models.CharField(default='Default Account Head', max_length=100)),
                ('location', models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class_first_year', 'G1 Class First Year'), ('g1_class_second_year', 'G1 Class Second Year'), ('g2_class_first_year', 'G2 Class First Year'), ('g2_class_second_year', 'G2 Class Second Year'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], default='isl_lab', max_length=50)),
            ],
        ),
    ]
