# Generated by Django 5.0.7 on 2024-07-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0003_asset_asset_id_asset_brand_asset_graphics_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hardware_type',
            field=models.CharField(blank=True, choices=[('computer', 'Computer'), ('projector', 'Projector'), ('switch', 'Switch'), ('tubelight', 'Tubelight'), ('fan', 'Fan'), ('smartboard', 'Smartboard'), ('projector_screen', 'Projector Screen')], max_length=50),
        ),
    ]
