# Generated by Django 5.0.7 on 2024-09-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0004_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerPeripherals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('type_of_asset', models.CharField(default='Computer Peripheral', max_length=50)),
                ('peripheral_type', models.CharField(choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('monitor', 'Monitor'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('ups', 'UPS'), ('projector', 'Projector'), ('external_hard_drive', 'External Hard Drive'), ('router', 'Router'), ('switch', 'Switch'), ('webcam', 'Webcam'), ('hdmi_cable', 'HDMI Cable'), ('vga_cable', 'VGA Cable'), ('usb_cable', 'USB Cable'), ('ethernet_cable', 'Ethernet Cable'), ('power_cable', 'Power Cable'), ('adapter', 'Adapter')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField(default='2000-01-01')),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class_first_year', 'G1 Class First Year'), ('g1_class_second_year', 'G1 Class Second Year'), ('g2_class_first_year', 'G2 Class First Year'), ('g2_class_second_year', 'G2 Class Second Year'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], default='isl_lab', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='computerhardware',
            name='ASSET_ID',
            field=models.CharField(default='CHW-XXX', max_length=50),
        ),
        migrations.AlterField(
            model_name='computerhardware',
            name='account_head',
            field=models.CharField(default='Acc Head', max_length=100),
        ),
        migrations.AlterField(
            model_name='computerhardware',
            name='hardware_type',
            field=models.CharField(default='Computer', max_length=50),
        ),
        migrations.AlterField(
            model_name='computerhardware',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class_first_year', 'G1 Class First Year'), ('g1_class_second_year', 'G1 Class Second Year'), ('g2_class_first_year', 'G2 Class First Year'), ('g2_class_second_year', 'G2 Class Second Year'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='ASSET_ID',
            field=models.CharField(default='SW-XXX', max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='account_head',
            field=models.CharField(default='Acc Head', max_length=100),
        ),
        migrations.AlterField(
            model_name='software',
            name='brand',
            field=models.CharField(blank=True, default='Brand name', max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class_first_year', 'G1 Class First Year'), ('g1_class_second_year', 'G1 Class Second Year'), ('g2_class_first_year', 'G2 Class First Year'), ('g2_class_second_year', 'G2 Class Second Year'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='model',
            field=models.CharField(blank=True, default='Model number', max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='stock_register_number',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
