# Generated by Django 5.0.7 on 2024-07-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0004_alter_asset_hardware_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='make_and_model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='specifications',
        ),
    ]
