# Generated by Django 5.0.7 on 2024-09-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0005_computerperipherals_alter_computerhardware_asset_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('software_version', models.CharField(max_length=50)),
                ('date_of_purchase', models.DateField()),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
