# Generated by Django 5.0.7 on 2024-09-06 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0006_softwareupdatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerHardwareUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('processor', models.CharField(max_length=50)),
                ('processor_generation', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('rom', models.CharField(blank=True, max_length=50)),
                ('motherboard', models.CharField(blank=True, max_length=50)),
                ('power_supply', models.CharField(blank=True, max_length=50)),
                ('graphics_card', models.CharField(blank=True, max_length=50)),
                ('date_of_purchase', models.DateField()),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('computer_hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMTSapp.computerhardware')),
            ],
        ),
    ]
