# Generated by Django 5.0.7 on 2024-09-09 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0007_computerhardwareupdatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectorUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=10)),
                ('lumens', models.IntegerField()),
                ('contrast_ratio', models.CharField(max_length=20)),
                ('connectivity', models.CharField(max_length=50)),
                ('lamp_life_hours', models.IntegerField()),
                ('date_of_purchase', models.DateField()),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('projector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMTSapp.projector')),
            ],
        ),
    ]
