# Generated by Django 5.0.7 on 2024-09-09 09:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0008_projectorupdatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publishing_house', models.CharField(max_length=255)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_purchase', models.DateField()),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_logged', models.DateField(default=django.utils.timezone.now)),
                ('date_of_update', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMTSapp.books')),
            ],
        ),
    ]
