# Generated by Django 5.0.7 on 2024-09-11 11:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0009_bookupdatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerPeripheralsUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peripheral_type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField()),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('date_logged', models.DateField(default=django.utils.timezone.now)),
                ('date_of_update', models.DateField()),
                ('peripheral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMTSapp.computerperipherals')),
            ],
        ),
    ]
