# Generated by Django 5.0.7 on 2024-09-14 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0010_computerperipheralsupdatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='software_photo',
            field=models.ImageField(blank=True, null=True, upload_to='software_photos/'),
        ),
        migrations.AlterField(
            model_name='software',
            name='ASSET_ID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='account_head',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='software',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='date_of_purchase',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='software',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='stock_register_number',
            field=models.CharField(max_length=50),
        ),
    ]
