# Generated by Django 5.0.7 on 2024-09-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0011_software_software_photo_alter_software_asset_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='software_photo',
        ),
    ]
