# Generated by Django 5.0.7 on 2024-09-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0013_connectivityoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projector',
            name='connectivity',
        ),
        migrations.DeleteModel(
            name='ConnectivityOption',
        ),
        migrations.AddField(
            model_name='projector',
            name='connectivity',
            field=models.CharField(choices=[('HDMI', 'HDMI'), ('VGA', 'VGA'), ('DVI', 'DVI'), ('USB', 'USB'), ('Wireless', 'Wireless')], max_length=50, null=True),
        ),
    ]
