# Generated by Django 5.0.7 on 2024-09-14 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0014_remove_projector_connectivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='account_head',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='date_of_purchase',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class_first_year', 'G1 Class First Year'), ('g1_class_second_year', 'G1 Class Second Year'), ('g2_class_first_year', 'G2 Class First Year'), ('g2_class_second_year', 'G2 Class Second Year'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='stock_register_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='computerperipherals',
            name='date_of_purchase',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='computerperipherals',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class_first_year', 'G1 Class First Year'), ('g1_class_second_year', 'G1 Class Second Year'), ('g2_class_first_year', 'G2 Class First Year'), ('g2_class_second_year', 'G2 Class Second Year'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], max_length=50),
        ),
    ]
