# Generated by Django 5.0.7 on 2024-09-14 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0015_alter_books_account_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareupdatelog',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projector',
            name='type_of_asset',
            field=models.CharField(default='PROJECTOR', max_length=50),
        ),
    ]
