# Generated by Django 5.0.7 on 2024-09-15 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0016_softwareupdatelog_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerhardwareupdatelog',
            name='date_of_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
