# Generated by Django 5.0.7 on 2024-09-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0017_computerhardwareupdatelog_date_of_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidSoftwareEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('date_of_purchase', models.DateField()),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('type_of_asset', models.CharField(max_length=50)),
                ('software_version', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_movement', models.DateField()),
                ('reason', models.TextField()),
                ('date_logged', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrappedSoftwareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('date_of_purchase', models.DateField()),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('type_of_asset', models.CharField(max_length=50)),
                ('software_version', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_movement', models.DateField()),
                ('reason', models.TextField()),
                ('date_logged', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
