# Generated by Django 5.0.7 on 2024-09-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0019_invalidcomputerhardwareentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidProjectorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('resolution', models.CharField(max_length=10)),
                ('lumens', models.IntegerField()),
                ('contrast_ratio', models.CharField(blank=True, max_length=20)),
                ('connectivity', models.CharField(max_length=50)),
                ('lamp_life_hours', models.IntegerField()),
                ('date_of_purchase', models.DateField()),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('type_of_asset', models.CharField(max_length=50)),
                ('date_of_movement', models.DateField()),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrappedProjectorAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('resolution', models.CharField(max_length=10)),
                ('lumens', models.IntegerField()),
                ('contrast_ratio', models.CharField(blank=True, max_length=20)),
                ('connectivity', models.CharField(max_length=50)),
                ('lamp_life_hours', models.IntegerField()),
                ('date_of_purchase', models.DateField()),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('type_of_asset', models.CharField(max_length=50)),
                ('date_of_movement', models.DateField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
