# Generated by Django 5.0.7 on 2024-09-24 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0021_invalidprojectorentry_date_logged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('software_version', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_purchase', models.DateField()),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('original_location', models.CharField(max_length=50)),
                ('movement_type', models.CharField(choices=[('within_college', 'Within the College'), ('outside', 'Outside the College')], max_length=20)),
                ('new_location', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('date_of_movement', models.DateField()),
                ('date_logged', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
