# Generated by Django 5.0.7 on 2024-09-26 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0023_computerhardwaremovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectorMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('resolution', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('4K', '4K')], max_length=10)),
                ('lumens', models.IntegerField(default=2000)),
                ('contrast_ratio', models.CharField(blank=True, max_length=20)),
                ('connectivity', models.CharField(blank=True, max_length=50, null=True)),
                ('lamp_life_hours', models.IntegerField(default=2000)),
                ('date_of_purchase', models.DateField(default=datetime.date.today)),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('movement_type', models.CharField(choices=[('within_college', 'Within the College'), ('outside', 'Outside the College')], max_length=20)),
                ('new_location', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('date_of_movement', models.DateField()),
                ('date_logged', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
