# Generated by Django 5.0.7 on 2024-09-30 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0025_invalidbookentry_scrappedbookasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidComputerPeripherals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('type_of_asset', models.CharField(default='Computer Peripheral', max_length=50)),
                ('peripheral_type', models.CharField(choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('monitor', 'Monitor'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('ups', 'UPS'), ('projector', 'Projector'), ('external_hard_drive', 'External Hard Drive'), ('router', 'Router'), ('switch', 'Switch'), ('webcam', 'Webcam'), ('hdmi_cable', 'HDMI Cable'), ('vga_cable', 'VGA Cable'), ('usb_cable', 'USB Cable'), ('ethernet_cable', 'Ethernet Cable'), ('power_cable', 'Power Cable'), ('adapter', 'Adapter')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField(default=datetime.date.today)),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class_first_year', 'G1 Class First Year'), ('g1_class_second_year', 'G1 Class Second Year'), ('g2_class_first_year', 'G2 Class First Year'), ('g2_class_second_year', 'G2 Class Second Year'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], max_length=50)),
                ('date_of_movement', models.DateField(default=datetime.date.today)),
                ('reason', models.TextField()),
                ('date_logged', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ScrappedComputerPeripherals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('type_of_asset', models.CharField(default='Computer Peripheral', max_length=50)),
                ('peripheral_type', models.CharField(choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('monitor', 'Monitor'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('ups', 'UPS'), ('projector', 'Projector'), ('external_hard_drive', 'External Hard Drive'), ('router', 'Router'), ('switch', 'Switch'), ('webcam', 'Webcam'), ('hdmi_cable', 'HDMI Cable'), ('vga_cable', 'VGA Cable'), ('usb_cable', 'USB Cable'), ('ethernet_cable', 'Ethernet Cable'), ('power_cable', 'Power Cable'), ('adapter', 'Adapter')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField(default=datetime.date.today)),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class_first_year', 'G1 Class First Year'), ('g1_class_second_year', 'G1 Class Second Year'), ('g2_class_first_year', 'G2 Class First Year'), ('g2_class_second_year', 'G2 Class Second Year'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], max_length=50)),
                ('date_of_movement', models.DateField(default=datetime.date.today)),
                ('reason', models.TextField()),
                ('date_logged', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
