# Generated by Django 5.0.7 on 2024-10-02 08:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0026_invalidcomputerperipherals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('within_college', 'Within College'), ('outside_college', 'Outside College')], max_length=20)),
                ('date_of_movement', models.DateField(default=datetime.date.today)),
                ('new_location', models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('g1_class_first_year', 'G1 Class First Year'), ('g1_class_second_year', 'G1 Class Second Year'), ('g2_class_first_year', 'G2 Class First Year'), ('g2_class_second_year', 'G2 Class Second Year'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], max_length=50)),
                ('reason_for_movement', models.TextField()),
                ('original_location', models.CharField(max_length=50)),
                ('original_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AMTSapp.books')),
            ],
        ),
    ]
