# Generated by Django 5.0.7 on 2024-10-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0027_movedbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movedbooks',
            name='new_location',
            field=models.CharField(max_length=255),
        ),
    ]
