# Generated by Django 5.0.7 on 2024-10-02 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0029_remove_movedbooks_original_book_movedbooks_asset_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovedComputerPeripherals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('type_of_asset', models.CharField(default='Computer Peripheral', max_length=50)),
                ('peripheral_type', models.CharField(choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('monitor', 'Monitor'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('ups', 'UPS'), ('projector', 'Projector'), ('external_hard_drive', 'External Hard Drive'), ('router', 'Router'), ('switch', 'Switch'), ('webcam', 'Webcam'), ('hdmi_cable', 'HDMI Cable'), ('vga_cable', 'VGA Cable'), ('usb_cable', 'USB Cable'), ('ethernet_cable', 'Ethernet Cable'), ('power_cable', 'Power Cable'), ('adapter', 'Adapter')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField(default=datetime.date.today)),
                ('stock_register_number', models.CharField(max_length=50)),
                ('account_head', models.CharField(max_length=100)),
                ('original_location', models.CharField(max_length=50)),
                ('movement_type', models.CharField(choices=[('within_college', 'Within College'), ('outside_college', 'Outside College')], max_length=20)),
                ('date_of_movement', models.DateField(default=datetime.date.today)),
                ('new_location', models.CharField(max_length=255)),
                ('reason_for_movement', models.TextField()),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
