# Generated by Django 5.0.7 on 2024-10-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0034_bookupdatelog_logged_by_bookupdatelog_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerperipheralsupdatelog',
            name='logged_by',
            field=models.CharField(default='MCA', max_length=100),
        ),
        migrations.AddField(
            model_name='computerperipheralsupdatelog',
            name='updated_by',
            field=models.CharField(default='Lab Incharge', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('K505_seminar_hall', 'K505-Seminar Hall'), ('e_learning_center', 'E-learning-Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='computerhardware',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('K505_seminar_hall', 'K505-Seminar-Hall'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('e_learning_center', 'E-learning-Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='computerperipherals',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('K505_seminar_hall', 'K505-Seminar Hall'), ('e_learning_center', 'E-learning-Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='invalidcomputerperipherals',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('K505_seminar_hall', 'K505-Seminar Hall'), ('e_learning_center', 'E-learning-Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projector',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('K505_seminar_hall', 'K505-Seminar Hall'), ('e_learning_center', 'E-learning-Center'), ('wireless_communication_lab', 'Wireless Communication Laboratory')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scrappedcomputerperipherals',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('K505_seminar_hall', 'K505-Seminar Hall'), ('e_learning_center', 'E-learning-Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('K505_seminar_hall', 'K505-Seminar Hall'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('library', 'Library')], max_length=50),
        ),
    ]
