# Generated by Django 5.0.7 on 2024-10-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0035_computerperipheralsupdatelog_logged_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('ASSET_ID', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_furniture', models.CharField(choices=[('desk', 'Desk'), ('chair', 'Chair'), ('cupboard', 'Cupboard'), ('almirah', 'Almirah'), ('table', 'Table'), ('board', 'Board')], max_length=50)),
                ('subtype', models.CharField(choices=[('desk_with_cupboard', 'Desk with Cupboard'), ('desk_without_cupboard', 'Desk without Cupboards'), ('2_seater_working_table', '2 Seater Working Table'), ('3_seater_working_table', '3 Seater Working Table'), ('chair_with_study_desk', 'Chair with Study Desk Attached'), ('wooden_chair', 'Wooden Chair'), ('steel_chair', 'Steel Chair'), ('metal_revolving_chair', 'Metal Revolving Chair'), ('conference_table', 'Conference Table'), ('conference_chair', 'Conference Chair')], max_length=50)),
                ('date_of_purchase', models.DateField()),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('k505_seminar_hall', 'K505-Seminar Hall'), ('e_learning_center', 'E-learning Center')], max_length=50)),
            ],
        ),
    ]
