# Generated by Django 5.0.7 on 2024-10-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0036_furniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='ASSET_ID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
