# Generated by Django 5.0.7 on 2024-10-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0037_alter_furniture_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='location',
            field=models.CharField(choices=[('isl_lab', 'ISL Lab'), ('cc_lab', 'CC Lab'), ('project_lab', 'Project Lab'), ('ibm_lab', 'IBM Lab'), ('wireless_communication_lab', 'Wireless Communication Laboratory'), ('K505_seminar_hall', 'K505-Seminar Hall'), ('e_learning_center', 'E-learning Center')], max_length=50),
        ),
    ]
