# Generated by Django 5.0.7 on 2024-10-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0038_alter_furniture_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='subtype',
            field=models.CharField(choices=[('desk_with_cupboard', 'Desk with Cupboard'), ('desk_without_cupboard', 'Desk without Cupboards'), ('2_seater_working_table', '2 Seater Working Table'), ('3_seater_working_table', '3 Seater Working Table'), ('chair_with_study_desk', 'Chair with Study Desk Attached'), ('wooden_chair', 'Wooden Chair'), ('steel_chair', 'Steel Chair'), ('metal_revolving_chair', 'Metal Revolving Chair'), ('conference_table', 'Conference Table'), ('whiteboard', 'Whiteboard'), ('blackboard', 'Blackboard'), ('pinboard', 'Pinboard'), ('noticeboard', 'Noticeboard')], max_length=50),
        ),
    ]
