# Generated by Django 5.0.7 on 2024-10-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0040_alter_furniture_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='subtype',
            field=models.CharField(choices=[('Desk with Cupboard', 'Desk with Cupboard'), ('Desk without Cupboards', 'Desk without Cupboards'), ('2 Seater Working Table', '2 Seater Working Table'), ('3 Seater Working Table', '3 Seater Working Table'), ('Chair with Study Desk Attached', 'Chair with Study Desk Attached'), ('Wooden chair', 'Wooden Chair'), ('Steel chair', 'Steel Chair'), ('Metal Revolving Chair', 'Metal Revolving Chair'), ('Conference Table', 'Conference Table'), ('Whiteboard', 'Whiteboard'), ('Blackboard', 'Blackboard'), ('Pinboard', 'Pinboard'), ('Noticeboard', 'Noticeboard')], max_length=50),
        ),
    ]
