# Generated by Django 5.0.7 on 2024-10-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0041_alter_furniture_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='type_of_furniture',
            field=models.CharField(choices=[('Desk', 'Desk'), ('Chair', 'Chair'), ('Cupboard', 'Cupboard'), ('Almirah', 'Almirah'), ('Table', 'Table'), ('Board', 'Board')], max_length=50),
        ),
    ]
