# Generated by Django 5.0.7 on 2024-10-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0042_alter_furniture_type_of_furniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='location',
            field=models.CharField(choices=[('ISL Lab', 'ISL Lab'), ('CC Lab', 'CC Lab'), ('Project Lab', 'Project Lab'), ('iIBM Lab', 'IBM Lab'), ('K505-Seminar Hall', 'K505-Seminar Hall'), ('Wireless Communication Laboratory', 'Wireless Communication Laboratory'), ('E-learning Center', 'E-learning Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='computerhardware',
            name='location',
            field=models.CharField(choices=[('ISL Lab', 'ISL Lab'), ('CC Lab', 'CC Lab'), ('Project Lab', 'Project Lab'), ('iIBM Lab', 'IBM Lab'), ('K505-Seminar Hall', 'K505-Seminar Hall'), ('Wireless Communication Laboratory', 'Wireless Communication Laboratory'), ('E-learning Center', 'E-learning Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='computerperipherals',
            name='location',
            field=models.CharField(choices=[('ISL Lab', 'ISL Lab'), ('CC Lab', 'CC Lab'), ('Project Lab', 'Project Lab'), ('iIBM Lab', 'IBM Lab'), ('K505-Seminar Hall', 'K505-Seminar Hall'), ('Wireless Communication Laboratory', 'Wireless Communication Laboratory'), ('E-learning Center', 'E-learning Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='location',
            field=models.CharField(choices=[('ISL Lab', 'ISL Lab'), ('CC Lab', 'CC Lab'), ('Project Lab', 'Project Lab'), ('iIBM Lab', 'IBM Lab'), ('K505-Seminar Hall', 'K505-Seminar Hall'), ('Wireless Communication Laboratory', 'Wireless Communication Laboratory'), ('E-learning Center', 'E-learning Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='subtype',
            field=models.CharField(choices=[('Desk with Cupboard', 'Desk with Cupboard'), ('Desk without Cupboards', 'Desk without Cupboards'), ('2 Seater Working Table', '2 Seater Working Table'), ('3 Seater Working Table', '3 Seater Working Table'), ('Chair with Study Desk Attached', 'Chair with Study Desk Attached'), ('Wooden chair', 'Wooden Chair'), ('Steel chair', 'Steel Chair'), ('Metal Revolving Chair', 'Metal Revolving Chair'), ('Conference Table', 'Conference Table'), ('Whiteboard', 'Whiteboard'), ('Blackboard', 'Blackboard'), ('Pinboard', 'Pinboard'), ('Noticeboard', 'Noticeboard'), ('Wooden Almirah', 'Wooden Almirah'), ('Steel Almirah', 'Steel Almirah'), ('Wooden Cupboard', 'Wooden Cupboard'), ('Steel Cupboard', 'Steel Cupboard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='invalidcomputerperipherals',
            name='location',
            field=models.CharField(choices=[('ISL Lab', 'ISL Lab'), ('CC Lab', 'CC Lab'), ('Project Lab', 'Project Lab'), ('iIBM Lab', 'IBM Lab'), ('K505-Seminar Hall', 'K505-Seminar Hall'), ('Wireless Communication Laboratory', 'Wireless Communication Laboratory'), ('E-learning Center', 'E-learning Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projector',
            name='location',
            field=models.CharField(choices=[('ISL Lab', 'ISL Lab'), ('CC Lab', 'CC Lab'), ('Project Lab', 'Project Lab'), ('iIBM Lab', 'IBM Lab'), ('K505-Seminar Hall', 'K505-Seminar Hall'), ('Wireless Communication Laboratory', 'Wireless Communication Laboratory'), ('E-learning Center', 'E-learning Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scrappedcomputerperipherals',
            name='location',
            field=models.CharField(choices=[('ISL Lab', 'ISL Lab'), ('CC Lab', 'CC Lab'), ('Project Lab', 'Project Lab'), ('iIBM Lab', 'IBM Lab'), ('K505-Seminar Hall', 'K505-Seminar Hall'), ('Wireless Communication Laboratory', 'Wireless Communication Laboratory'), ('E-learning Center', 'E-learning Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='location',
            field=models.CharField(choices=[('ISL Lab', 'ISL Lab'), ('CC Lab', 'CC Lab'), ('Project Lab', 'Project Lab'), ('iIBM Lab', 'IBM Lab'), ('K505-Seminar Hall', 'K505-Seminar Hall'), ('Wireless Communication Laboratory', 'Wireless Communication Laboratory'), ('E-learning Center', 'E-learning Center')], max_length=50),
        ),
    ]
