# Generated by Django 5.0.7 on 2024-10-14 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0044_furnitureupdatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureupdatelog',
            name='date_logged',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
