# Generated by Django 5.0.7 on 2024-10-14 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0045_furnitureupdatelog_date_logged'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('type_of_furniture', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=50)),
                ('date_of_purchase', models.DateField(default=datetime.date.today)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('date_of_movement', models.DateField(default=datetime.date.today)),
                ('reason_for_invalidity', models.TextField()),
                ('date_logged', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ScrappedFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_ID', models.CharField(max_length=50)),
                ('type_of_furniture', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=50)),
                ('date_of_purchase', models.DateField(default=datetime.date.today)),
                ('account_head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('date_of_movement', models.DateField(default=datetime.date.today)),
                ('reason_for_scrapping', models.TextField()),
                ('date_logged', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
