# Generated by Django 5.0.7 on 2024-10-20 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMTSapp', '0046_invalidfurniture_scrappedfurniture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(max_length=100)),
                ('desk_asset_id', models.CharField(blank=True, max_length=50)),
                ('desk_make', models.CharField(blank=True, max_length=100)),
                ('desk_model', models.CharField(blank=True, max_length=100)),
                ('desk_stock_register_number', models.CharField(blank=True, max_length=50)),
                ('desk_account_head', models.CharField(blank=True, max_length=100)),
                ('desk_date_of_purchase', models.DateField(default=django.utils.timezone.now)),
                ('chair_asset_id', models.CharField(blank=True, max_length=50)),
                ('chair_make', models.CharField(blank=True, max_length=100)),
                ('chair_model', models.CharField(blank=True, max_length=100)),
                ('chair_stock_register_number', models.CharField(blank=True, max_length=50)),
                ('chair_account_head', models.CharField(blank=True, max_length=100)),
                ('chair_date_of_purchase', models.DateField(default=django.utils.timezone.now)),
                ('cupboard_asset_id', models.CharField(blank=True, max_length=50)),
                ('cupboard_make', models.CharField(blank=True, max_length=100)),
                ('cupboard_model', models.CharField(blank=True, max_length=100)),
                ('cupboard_stock_register_number', models.CharField(blank=True, max_length=50)),
                ('cupboard_account_head', models.CharField(blank=True, max_length=100)),
                ('cupboard_date_of_purchase', models.DateField(default=django.utils.timezone.now)),
                ('computer_asset_id', models.CharField(blank=True, max_length=50)),
                ('computer_make', models.CharField(blank=True, max_length=100)),
                ('computer_model', models.CharField(blank=True, max_length=100)),
                ('computer_stock_register_number', models.CharField(blank=True, max_length=50)),
                ('computer_account_head', models.CharField(blank=True, max_length=100)),
                ('computer_date_of_purchase', models.DateField(default=django.utils.timezone.now)),
                ('monitor_asset_id', models.CharField(blank=True, max_length=50)),
                ('monitor_make', models.CharField(blank=True, max_length=100)),
                ('monitor_model', models.CharField(blank=True, max_length=100)),
                ('monitor_stock_register_number', models.CharField(blank=True, max_length=50)),
                ('monitor_account_head', models.CharField(blank=True, max_length=100)),
                ('monitor_date_of_purchase', models.DateField(default=django.utils.timezone.now)),
                ('mouse_asset_id', models.CharField(blank=True, max_length=50)),
                ('mouse_make', models.CharField(blank=True, max_length=100)),
                ('mouse_model', models.CharField(blank=True, max_length=100)),
                ('mouse_stock_register_number', models.CharField(blank=True, max_length=50)),
                ('mouse_account_head', models.CharField(blank=True, max_length=100)),
                ('mouse_date_of_purchase', models.DateField(default=django.utils.timezone.now)),
                ('keyboard_asset_id', models.CharField(blank=True, max_length=50)),
                ('keyboard_make', models.CharField(blank=True, max_length=100)),
                ('keyboard_model', models.CharField(blank=True, max_length=100)),
                ('keyboard_stock_register_number', models.CharField(blank=True, max_length=50)),
                ('keyboard_account_head', models.CharField(blank=True, max_length=100)),
                ('keyboard_date_of_purchase', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
